### ISSUE TITLE
validate: detect template placeholders

### ISSUE THREAD

**Issue by tronghn** [nais/cli#321]
When attempting to validate a resource that contains template placeholders e.g:

```yaml
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: some-app
  namespace: some-team
  labels:
    team: some-team
spec:
  image: {{image}}
```

a somewhat cryptic error is returned:

```shell
failed to convert yaml to json: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"image":interface {}(nil)}
```

This is of course due to `{}` being parsed as a map for the `image` field in the above example.

In case a given resource contains placeholders, we should consider doing the following:

1. Return a more appropriate error message.
2. Inform the user of the available templating support to fix the errors.

For fields that expect string values we could consider automatically wrapping the placeholders with quotes, but this seems hacky.
